BWDotNetTrainingBatch5.ChartWebApp/Controllers/ApexChartController.cs
using BWDotNetTrainingBatch5.ChartWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BWDotNetTrainingBatch5.ChartWebApp.Controllers
{
    public class ApexChartController : Controller
    {
        public IActionResult PieChart()
        {
            ApexChartPieChartModel model = new ApexChartPieChartModel();
            model.Series = new int[] { 44, 55, 13, 43, 22 };
            model.Labels = new string[] { "Team A", "Team B", "Team C", "Team D", "Team E" };
            return View(model);
        }
        
        public IActionResult MixedChart()
        {
            ApexChartMixedChartModel model = new ApexChartMixedChartModel();
    
            model.Series = new List<SeriesData>
            {
                new SeriesData
                {
                    Name = "TEAM A",
                    Type = "column",
                    Data = new int[] { 23, 11, 22, 27, 13, 22, 37, 21, 44, 22, 30 }
                },
                new SeriesData
                {
                    Name = "TEAM B",
                    Type = "area",
                    Data = new int[] { 44, 55, 41, 67, 22, 43, 21, 41, 56, 27, 43 }
                },
                new SeriesData
                {
                    Name = "TEAM C",
                    Type = "line",
                    Data = new int[] { 30, 25, 36, 30, 45, 35, 64, 52, 59, 36, 39 }
                }
            };
    
            model.Labels = new string[] 
            { 
                "01/01/2003", "02/01/2003", "03/01/2003", "04/01/2003", 
                "05/01/2003", "06/01/2003", "07/01/2003", "08/01/2003", 
                "09/01/2003", "10/01/2003", "11/01/2003"
            };
    
            return View(model);
        }
        
        public IActionResult CandlestickChart()
        {
            ApexChartCandlestickModel model = new ApexChartCandlestickModel();
            
            model.LineData = new List<LineSeriesData>
            {
                new LineSeriesData { X = 1538778600000, Y = 6604 },
                new LineSeriesData { X = 1538782200000, Y = 6602 },
                new LineSeriesData { X = 1538814600000, Y = 6607 },
                new LineSeriesData { X = 1538884800000, Y = 6620 }
            };
            
            model.CandlestickData = new List<CandlestickSeriesData>
            {
                new CandlestickSeriesData { X = 1538778600000, Y = new decimal[] { 6629.81m, 6650.5m, 6623.04m, 6633.33m } },
                new CandlestickSeriesData { X = 1538780400000, Y = new decimal[] { 6632.01m, 6643.59m, 6620m, 6630.11m } },
                new CandlestickSeriesData { X = 1538782200000, Y = new decimal[] { 6630.71m, 6648.95m, 6623.34m, 6635.65m } },
                new CandlestickSeriesData { X = 1538784000000, Y = new decimal[] { 6635.65m, 6651m, 6629.67m, 6638.24m } },
                new CandlestickSeriesData { X = 1538785800000, Y = new decimal[] { 6638.24m, 6640m, 6620m, 6624.47m } },
                new CandlestickSeriesData { X = 1538787600000, Y = new decimal[] { 6624.53m, 6636.03m, 6621.68m, 6624.31m } },
                new CandlestickSeriesData { X = 1538789400000, Y = new decimal[] { 6624.61m, 6632.2m, 6617m, 6626.02m } },
                new CandlestickSeriesData { X = 1538791200000, Y = new decimal[] { 6627m, 6627.62m, 6584.22m, 6603.02m } },
                new CandlestickSeriesData { X = 1538793000000, Y = new decimal[] { 6605m, 6608.03m, 6598.95m, 6604.01m } },
                new CandlestickSeriesData { X = 1538794800000, Y = new decimal[] { 6604.5m, 6614.4m, 6602.26m, 6608.02m } },
                new CandlestickSeriesData { X = 1538796600000, Y = new decimal[] { 6608.02m, 6610.68m, 6601.99m, 6608.91m } },
                new CandlestickSeriesData { X = 1538798400000, Y = new decimal[] { 6608.91m, 6618.99m, 6608.01m, 6612m } },
                new CandlestickSeriesData { X = 1538800200000, Y = new decimal[] { 6612m, 6615.13m, 6605.09m, 6612m } },
                new CandlestickSeriesData { X = 1538802000000, Y = new decimal[] { 6612m, 6624.12m, 6608.43m, 6622.95m } },
                new CandlestickSeriesData { X = 1538803800000, Y = new decimal[] { 6623.91m, 6623.91m, 6615m, 6615.67m } },
                new CandlestickSeriesData { X = 1538805600000, Y = new decimal[] { 6618.69m, 6618.74m, 6610m, 6610.4m } },
                new CandlestickSeriesData { X = 1538807400000, Y = new decimal[] { 6611m, 6622.78m, 6610.4m, 6614.9m } },
                new CandlestickSeriesData { X = 1538809200000, Y = new decimal[] { 6614.9m, 6626.2m, 6613.33m, 6623.45m } },
                new CandlestickSeriesData { X = 1538811000000, Y = new decimal[] { 6623.48m, 6627m, 6618.38m, 6620.35m } },
                new CandlestickSeriesData { X = 1538812800000, Y = new decimal[] { 6619.43m, 6620.35m, 6610.05m, 6615.53m } },
                new CandlestickSeriesData { X = 1538814600000, Y = new decimal[] { 6615.53m, 6617.93m, 6610m, 6615.19m } },
                new CandlestickSeriesData { X = 1538816400000, Y = new decimal[] { 6615.19m, 6621.6m, 6608.2m, 6620m } },
                new CandlestickSeriesData { X = 1538818200000, Y = new decimal[] { 6619.54m, 6625.17m, 6614.15m, 6620m } },
                new CandlestickSeriesData { X = 1538820000000, Y = new decimal[] { 6620.33m, 6634.15m, 6617.24m, 6624.61m } },
                new CandlestickSeriesData { X = 1538821800000, Y = new decimal[] { 6625.95m, 6626m, 6611.66m, 6617.58m } },
                new CandlestickSeriesData { X = 1538823600000, Y = new decimal[] { 6619m, 6625.97m, 6595.27m, 6598.86m } },
                new CandlestickSeriesData { X = 1538825400000, Y = new decimal[] { 6598.86m, 6598.88m, 6570m, 6587.16m } },
                new CandlestickSeriesData { X = 1538827200000, Y = new decimal[] { 6588.86m, 6600m, 6580m, 6593.4m } },
                new CandlestickSeriesData { X = 1538829000000, Y = new decimal[] { 6593.99m, 6598.89m, 6585m, 6587.81m } },
                new CandlestickSeriesData { X = 1538830800000, Y = new decimal[] { 6587.81m, 6592.73m, 6567.14m, 6578m } },
                new CandlestickSeriesData { X = 1538832600000, Y = new decimal[] { 6578.35m, 6581.72m, 6567.39m, 6579m } },
                new CandlestickSeriesData { X = 1538834400000, Y = new decimal[] { 6579.38m, 6580.92m, 6566.77m, 6575.96m } },
                new CandlestickSeriesData { X = 1538836200000, Y = new decimal[] { 6575.96m, 6589m, 6571.77m, 6588.92m } },
                new CandlestickSeriesData { X = 1538838000000, Y = new decimal[] { 6588.92m, 6594m, 6577.55m, 6589.22m } },
                new CandlestickSeriesData { X = 1538839800000, Y = new decimal[] { 6589.3m, 6598.89m, 6589.1m, 6596.08m } },
                new CandlestickSeriesData { X = 1538841600000, Y = new decimal[] { 6597.5m, 6600m, 6588.39m, 6596.25m } },
                new CandlestickSeriesData { X = 1538843400000, Y = new decimal[] { 6598.03m, 6600m, 6588.73m, 6595.97m } },
                new CandlestickSeriesData { X = 1538845200000, Y = new decimal[] { 6595.97m, 6602.01m, 6588.17m, 6602m } },
                new CandlestickSeriesData { X = 1538847000000, Y = new decimal[] { 6602m, 6607m, 6596.51m, 6599.95m } },
                new CandlestickSeriesData { X = 1538848800000, Y = new decimal[] { 6600.63m, 6601.21m, 6590.39m, 6591.02m } },
                new CandlestickSeriesData { X = 1538850600000, Y = new decimal[] { 6591.02m, 6603.08m, 6591m, 6591m } },
                new CandlestickSeriesData { X = 1538852400000, Y = new decimal[] { 6591m, 6601.32m, 6585m, 6592m } },
                new CandlestickSeriesData { X = 1538854200000, Y = new decimal[] { 6593.13m, 6596.01m, 6590m, 6593.34m } },
                new CandlestickSeriesData { X = 1538856000000, Y = new decimal[] { 6593.34m, 6604.76m, 6582.63m, 6593.86m } },
                new CandlestickSeriesData { X = 1538857800000, Y = new decimal[] { 6593.86m, 6604.28m, 6586.57m, 6600.01m } },
                new CandlestickSeriesData { X = 1538859600000, Y = new decimal[] { 6601.81m, 6603.21m, 6592.78m, 6596.25m } },
                new CandlestickSeriesData { X = 1538861400000, Y = new decimal[] { 6596.25m, 6604.2m, 6590m, 6602.99m } },
                new CandlestickSeriesData { X = 1538863200000, Y = new decimal[] { 6602.99m, 6606m, 6584.99m, 6587.81m } },
                new CandlestickSeriesData { X = 1538865000000, Y = new decimal[] { 6587.81m, 6595m, 6583.27m, 6591.96m } },
                new CandlestickSeriesData { X = 1538866800000, Y = new decimal[] { 6591.97m, 6596.07m, 6585m, 6588.39m } },
                new CandlestickSeriesData { X = 1538868600000, Y = new decimal[] { 6587.6m, 6598.21m, 6587.6m, 6594.27m } },
                new CandlestickSeriesData { X = 1538870400000, Y = new decimal[] { 6596.44m, 6601m, 6590m, 6596.55m } },
                new CandlestickSeriesData { X = 1538872200000, Y = new decimal[] { 6598.91m, 6605m, 6596.61m, 6600.02m } },
                new CandlestickSeriesData { X = 1538874000000, Y = new decimal[] { 6600.55m, 6605m, 6589.14m, 6593.01m } },
                new CandlestickSeriesData { X = 1538875800000, Y = new decimal[] { 6593.15m, 6605m, 6592m, 6603.06m } },
                new CandlestickSeriesData { X = 1538877600000, Y = new decimal[] { 6603.07m, 6604.5m, 6599.09m, 6603.89m } },
                new CandlestickSeriesData { X = 1538879400000, Y = new decimal[] { 6604.44m, 6604.44m, 6600m, 6603.5m } },
                new CandlestickSeriesData { X = 1538881200000, Y = new decimal[] { 6603.5m, 6603.99m, 6597.5m, 6603.86m } },
                new CandlestickSeriesData { X = 1538883000000, Y = new decimal[] { 6603.85m, 6605m, 6600m, 6604.07m } },
                new CandlestickSeriesData { X = 1538884800000, Y = new decimal[] { 6604.98m, 6606m, 6604.07m, 6606m } }
            };
            
            return View(model);
        }
        
        public IActionResult ColumnChart()
        {
            ColumnChartModel model = new ColumnChartModel();
    

BWDotNetTrainingBatch5.ChartWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BWDotNetTrainingBatch5.ChartWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/BWDotNetTrainingBatch5.ChartWebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BWDotNetTrainingBatch5.ChartWebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="PieChart">Pie Chart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="MixedChart">Mixed Chart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="CandlestickChart">CandleStick Chart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="ColumnChart">Column Chart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="AreaChart">Area Chart</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - BWDotNetTrainingBatch5.ChartWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
@await RenderSectionAsync("scripts", required: false)
</body>
</html>